name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: docker

    steps:
      - uses: actions/checkout@v4

      - run: npm install
      - run: npm run build

      - name: Package
        run: tar -czf build.tar.gz dist/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: build.tar.gz