name: LocalBackup
version: '1.0'
main: com.bn_2k9.localBackup.LocalBackup
api-version: '1.20'
authors: [ BN_2K9 ]
description: An Great Backup Plugin!
commands:
  localBackup:
    aliases: lb
    permission: LocalBackup.Backup